db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/desarrollo_logisticpymes
db.username=postgres
db.password=buho123

cron.enabled=false
cron.task=false
fixedDelayMail.in.milliseconds=300000
fixedDelayTask.in.milliseconds=300000
fixedDelayApi.in.milliseconds=300000
fixedDelayAccount.in.milliseconds=300000

spring.main.allow-circular-references=true
spring.freemarker.checkTemplateLocation=false

