db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://190.27.41.78:5432/desarrollo_universal
db.username=postgres
db.password=buho123

cron.enabled=false
fixedDelayMail.in.milliseconds=300000
cron.task=false
fixedDelayTask.in.milliseconds=300000
fixedDelayApi.in.milliseconds=300000